# Umfrage Teil II

Deskriptive Analyse

## Daten importieren

In [3]:
import pandas as pd

df = pd.read_csv("data/clean_ws22.csv")

## Daten vorbereiten

In [4]:
# Liste mit den noch enthaltenen Original-Spalten erstellen
list_drop = df.filter(like='_orig', axis=1).columns.tolist()

list_drop.append('zeit')

# Wir entfernen die Original-Spalten und die Variable zeit
df = df.drop(columns=list_drop)

# Liste mit Dummy-Variablen erstellen
list_dummy = df.filter(like='__', axis=1).columns

# Dummy-Variablen als Objekt-Daten speichern
for i in list_dummy:
    df[i] = df[i].astype("object")

In [5]:
import numpy as np

# Liste für metrische Daten
list_metric = df.select_dtypes(include=[np.number]).columns.tolist()

# Liste für kategoriale Daten
list_cat = df.select_dtypes(include=['object']).columns.tolist()

# Kategoriale Daten formatieren

for i in list_cat:
    df[i] = df[i].astype("category")

## Datenüberblick

In [6]:
df

,sport,fleissig,entmutigen,talente,einkommen,energie,megacity,geleebohnen,soziale_medien,studium,...,alter,geschlecht,buch__Ja,buch__Nein,geschlecht__Männlich,geschlecht__Weiblich,sport_qm,fleissig_qm,talente_qm,entmutigen_qm
0,teils teils,trifft eher zu,trifft eher zu,trifft überhaupt nicht zu,9,42,4,3000,34,34,...,22,Männlich,1,0,1,0,3,4,1,4
1,trifft eher nicht zu,trifft eher nicht zu,trifft eher nicht zu,trifft eher zu,45,62,3,400,34,2,...,34,Weiblich,0,1,0,1,2,2,4,2
2,teils teils,trifft eher nicht zu,teils teils,trifft eher zu,34,82,5,4000,23,12,...,12,Männlich,1,0,1,0,3,2,4,3
3,trifft völlig zu,trifft eher zu,trifft eher zu,trifft eher nicht zu,61,62,3,586,180,60,...,23,Weiblich,1,0,0,1,5,4,2,4
4,trifft eher nicht zu,trifft völlig zu,trifft eher nicht zu,trifft eher nicht zu,43,62,2,350,120,200,...,23,Weiblich,1,0,0,1,2,5,2,2
5,trifft eher nicht zu,teils teils,trifft eher zu,trifft eher nicht zu,36,82,4,2700,150,60,...,26,Männlich,0,1,1,0,2,3,2,4
6,trifft überhaupt nicht zu,trifft eher zu,trifft eher zu,trifft eher nicht zu,60,82,2,999,240,180,...,22,Weiblich,1,0,0,1,1,4,2,4
7,trifft völlig zu,trifft eher zu,trifft eher zu,teils teils,61,62,2,500,2,180,...,25,Männlich,1,0,1,0,5,4,3,4
8,trifft eher zu,trifft eher zu,teils teils,teils teils,65,42,4,2136,200,60,...,24,Weiblich,1,0,0,1,4,4,3,3
9,trifft eher nicht zu,trifft eher nicht zu,trifft eher nicht zu,trifft eher nicht zu,40%,82,4,3000,240,60,...,23,Weiblich,1,0,0,1,2,2,2,2
10,trifft eher zu,trifft eher nicht zu,trifft eher zu,trifft überhaupt nicht zu,65,62,2,5221,60,15,...,22,Männlich,0,1,1,0,4,2,1,4
11,teils teils,trifft eher zu,trifft eher zu,teils teils,60,82,3,500,90,90,...,26,Weiblich,1,0,0,1,3,4,3,4
12,teils teils,trifft eher zu,trifft eher nicht zu,teils teils,80,82,1,3000,50,600,...,22,Weiblich,1,0,0,1,3,4,3,2
13,teils teils,trifft eher nicht zu,teils teils,trifft eher zu,70,82,2,2000,15,35,...,20,Weiblich,1,0,0,1,3,2,4,3
14,trifft eher zu,trifft eher zu,trifft eher nicht zu,teils teils,62,42,4,814,120,90,...,20,Weiblich,1,0,0,1,4,4,3,2
15,trifft überhaupt nicht zu,trifft völlig zu,trifft eher zu,trifft eher nicht zu,61,82,2,1000,120,120,...,21,Weiblich,1,0,0,1,1,5,2,4
16,trifft eher zu,teils teils,trifft eher nicht zu,trifft überhaupt nicht zu,60,82,2,1500,360,30,...,23,Weiblich,1,0,0,1,4,3,1,2
17,teils teils,teils teils,trifft eher zu,trifft eher nicht zu,40,82,2,2340,180,40,...,19,Weiblich,0,1,0,1,3,3,2,4
18,teils teils,trifft eher nicht zu,trifft eher zu,trifft überhaupt nicht zu,65,82,4,2057,100,120,...,20,Weiblich,1,0,0,1,3,2,1,4
19,teils teils,trifft eher nicht zu,trifft eher nicht zu,trifft eher zu,78,82,2,1624,180,45,...,20,Weiblich,1,0,0,1,3,2,4,2
20,trifft eher nicht zu,teils teils,trifft eher nicht zu,trifft überhaupt nicht zu,60,62,4,543,150,90,...,20,Weiblich,0,1,0,1,2,3,1,2
21,trifft völlig zu,teils teils,trifft überhaupt nicht zu,trifft eher nicht zu,61,82,5,5000,35,60,...,27,Männlich,0,1,1,0,5,3,2,1
22,trifft eher zu,teils teils,teils teils,trifft eher nicht zu,74,82,3,1423,90,120,...,26,Weiblich,1,0,0,1,4,3,2,3
23,trifft eher zu,trifft eher zu,teils teils,trifft eher nicht zu,70,82,4,2000,120,120,...,19,Weiblich,1,0,0,1,4,4,2,3
24,trifft eher zu,teils teils,teils teils,trifft eher nicht zu,62,62,2,1500,120,90,...,25,Weiblich,1,0,0,1,4,3,2,3
25,trifft eher nicht zu,teils teils,teils teils,teils teils,40,62,4,558,280,180,...,20,Weiblich,1,0,0,1,2,3,3,3
26,trifft eher nicht zu,trifft eher zu,teils teils,trifft eher nicht zu,67,82,2,486,120,180,...,20,Weiblich,1,0,0,1,2,4,2,3
27,trifft eher zu,teils teils,trifft eher nicht zu,trifft eher nicht zu,67,62,3,424,45,120,...,20,Weiblich,0,1,0,1,4,3,2,2
28,trifft eher nicht zu,trifft eher zu,trifft eher nicht zu,trifft eher nicht zu,61,62,2,1500,120,60,...,20,Weiblich,1,0,0,1,2,4,2,2
29,trifft völlig zu,trifft eher zu,trifft eher zu,teils teils,70,82,2,1989,90,60,...,20,Weiblich,0,1,0,1,5,4,3,4
30,teils teils,trifft eher zu,trifft eher zu,trifft eher nicht zu,70,82,4,1000,60,150,...,21,Weiblich,1,0,0,1,3,4,2,4
31,trifft eher nicht zu,trifft eher zu,trifft eher zu,teils teils,65%,62,2,200,3,2,...,21,Weiblich,1,0,0,1,2,4,3,4
32,trifft eher zu,trifft eher zu,trifft völlig zu,trifft eher nicht zu,20,62,3,300,5,100,...,21,Männlich,0,1,1,0,4,4,2,5
33,trifft eher zu,trifft eher nicht zu,teils teils,trifft eher nicht zu,40,82,2,332,120,60,...,20,Männlich,0,1,1,0,4,2,2,3
34,trifft eher zu,teils teils,trifft völlig zu,trifft überhaupt nicht zu,65,82,4,1350,30,60,...,24,Männlich,1,0,1,0,4,3,1,5
35,trifft völlig zu,trifft völlig zu,trifft völlig zu,trifft überhaupt nicht zu,15,82,4,750,15,4,...,24,Männlich,1,0,1,0,5,5,1,5
36,teils teils,trifft eher nicht zu,trifft eher zu,trifft eher nicht zu,55,62,2,2000,120,45,...,22,Männlich,0,1,1,0,3,2,2,4
37,teils teils,trifft eher zu,trifft eher nicht zu,trifft eher nicht zu,30,62,3,700,180,200,...,22,Weiblich,1,0,0,1,3,4,2,2

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   sport                 38 non-null     category
 1   fleissig              38 non-null     category
 2   entmutigen            38 non-null     category
 3   talente               38 non-null     category
 4   einkommen             38 non-null     category
 5   energie               38 non-null     int64
 6   megacity              38 non-null     int64
 7   geleebohnen           38 non-null     int64
 8   soziale_medien        38 non-null     int64
 9   studium               38 non-null     int64
 10  buch                  38 non-null     category
 11  alter                 38 non-null     int64
 12  geschlecht            38 non-null     category
 13  buch__Ja              38 non-null     category
 14  buch__Nein            38 non-null     category
 15  geschlecht__Männlich  38 non-null     category
 16  geschlecht__Weiblich  38 non-null     category
 17  sport_qm              38 non-null     int64
 18  fleissig_qm           38 non-null     int64
 19  talente_qm            38 non-null     int64
 20  entmutigen_qm         38 non-null     int64
dtypes: category(11), int64(10)
memory usage: 5.7 KB

## Deskriptive Analyse

Wir beginnnen mit der deskriptiven Analyse

### Kategoriale daten

In [8]:
df[list_cat].describe().T

                     count unique                   top freq
sport                   38      5           teils teils   11
fleissig                38      4        trifft eher zu   16
entmutigen              38      5        trifft eher zu   14
talente                 38      4  trifft eher nicht zu   19
einkommen               38     21                    61    5
buch                    38      2                    Ja   27
geschlecht              38      2              Weiblich   27
buch__Ja                38      2                     1   27
buch__Nein              38      2                     0   27
geschlecht__Männlich    38      2                     0   27
geschlecht__Weiblich    38      2                     1   27

In [9]:
for i in list_cat:
    print("-"*30)
    print(i, "\n", df[i].value_counts())

------------------------------
sport
 teils teils                  11
trifft eher zu               11
trifft eher nicht zu          9
trifft völlig zu              5
trifft überhaupt nicht zu     2
Name: sport, dtype: int64
------------------------------
fleissig
 trifft eher zu          16
teils teils             10
trifft eher nicht zu     9
trifft völlig zu         3
Name: fleissig, dtype: int64
------------------------------
entmutigen
 trifft eher zu               14
trifft eher nicht zu         11
teils teils                   9
trifft völlig zu              3
trifft überhaupt nicht zu     1
Name: entmutigen, dtype: int64
------------------------------
talente
 trifft eher nicht zu         19
teils teils                   8
trifft überhaupt nicht zu     7
trifft eher zu                4
Name: talente, dtype: int64
------------------------------
einkommen
 61     5
60     4
70     4
65     4
40     3
67     2
62     2
80     1
78     1
74     1
65%    1
15     1
20     1
55     1
45     1
43     1
40%    1
36     1
34     1
30     1
9      1
Name: einkommen, dtype: int64
------------------------------
buch
 Ja      27
Nein    11
Name: buch, dtype: int64
------------------------------
geschlecht
 Weiblich    27
Männlich    11
Name: geschlecht, dtype: int64
------------------------------
buch__Ja
 1    27
0    11
Name: buch__Ja, dtype: int64
------------------------------
buch__Nein
 0    27
1    11
Name: buch__Nein, dtype: int64
------------------------------
geschlecht__Männlich
 0    27
1    11
Name: geschlecht__Männlich, dtype: int64
------------------------------
geschlecht__Weiblich
 1    27
0    11
Name: geschlecht__Weiblich, dtype: int64

### Numerische Daten

In [10]:
df[list_metric].describe().round(2).T

,count,mean,std,min,25%,50%,75%,max
energie,38.0,71.47,12.93,42.0,62.00,82.0,82.00,82.0
megacity,38.0,2.95,1.04,1.0,2.00,3.0,4.00,5.0
geleebohnen,38.0,1573.21,1263.42,200.0,546.75,1386.5,2042.75,5221.0
soziale_medien,38.0,110.55,82.93,2.0,37.50,120.0,150.00,360.0
studium,38.0,98.26,101.52,2.0,45.00,60.0,120.00,600.0
alter,38.0,22.08,3.36,12.0,20.00,22.0,23.75,34.0
sport_qm,38.0,3.21,1.12,1.0,2.00,3.0,4.00,5.0
fleissig_qm,38.0,3.34,0.94,2.0,3.00,3.5,4.00,5.0
talente_qm,38.0,2.24,0.88,1.0,2.00,2.0,3.00,4.0
entmutigen_qm,38.0,3.18,1.04,1.0,2.00,3.0,4.00,5.0